s1 = 'Hugo'
s2 = str('Hugo')
s3 = str(42)

list1 = list()
list2 = list([1, 2,3])

e = Exception('ein fehler ist passiert')

print(type(e))